import type { ResumeTemplate } from '@/types/resume'
import { makeLayout, FONTS } from '../helper'
import './style.css'

/** 经典分类模板 */
export const classicTemplates: ResumeTemplate[] = [
  {
    id: 'cls-leader',
    name: '点线雅紫',
    category: 'classic',
    desc: '点状引导线标题，头部姓名与信息两端分布',
    className: 'tpl-cls-leader',
    layout: makeLayout({ themeColor: '#6d4fa3', moduleSpacing: 14, pageMargin: 12 }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'cls-pill',
    name: '胶囊横幅',
    category: 'classic',
    desc: '圆角横幅头部 + 胶囊式模块标题，两栏信息三栏条目',
    className: 'tpl-cls-pill',
    layout: makeLayout({ themeColor: '#5e7fa0', moduleSpacing: 14, pageMargin: 12 }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'cls-tag',
    name: '经典',
    category: 'classic',
    desc: '标签式模块标题，时间居左三栏条目，经典商务风',
    className: 'tpl-cls-tag',
    layout: makeLayout({ themeColor: '#5b7a8c', moduleSpacing: 14, pageMargin: 12 }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'cls-song',
    name: '宋体雅致',
    category: 'classic',
    desc: '宋体正文，传统正式风格',
    className: 'tpl-cls-song',
    layout: makeLayout({ fontFamily: FONTS.SONG, fontSize: 15, lineHeight: 1.6, pageMargin: 12 }),
    titleStyle: 'underline',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'cls-center',
    name: '居中典雅',
    category: 'classic',
    desc: '个人信息与标题居中，对称庄重',
    className: 'tpl-cls-center',
    layout: makeLayout({ fontFamily: FONTS.HEI, moduleSpacing: 14 }),
    titleStyle: 'center',
    profileStyle: 'center',
    pageStyle: 'single',
  },
  {
    id: 'cls-bar-blue',
    name: '蓝色竖条',
    category: 'classic',
    desc: '姓名居中，蓝色竖条标题，干净清爽',
    className: 'tpl-cls-bar-blue',
    layout: makeLayout({ themeColor: '#2c6ec8', moduleSpacing: 12 }),
    titleStyle: 'sidebar',
    profileStyle: 'center',
    pageStyle: 'single',
  },
  {
    id: 'cls-frame-red',
    name: '红条居中',
    category: 'classic',
    desc: '顶部红条 + 姓名居中，喜庆正式',
    className: 'tpl-cls-frame-red',
    layout: makeLayout({ themeColor: '#b03a3a', moduleSpacing: 12, pageMargin: 12 }),
    titleStyle: 'sidebar',
    profileStyle: 'center',
    pageStyle: 'single',
  },
  {
    id: 'cls-topline-blue',
    name: '蓝条左置',
    category: 'classic',
    desc: '顶部蓝条 + 姓名左置，干练利落',
    className: 'tpl-cls-topline-blue',
    layout: makeLayout({ themeColor: '#2f6fd6', moduleSpacing: 12 }),
    titleStyle: 'underline',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'cls-topline-red',
    name: '红条左置',
    category: 'classic',
    desc: '顶部红条 + 姓名左置，大气醒目',
    className: 'tpl-cls-topline-red',
    layout: makeLayout({ themeColor: '#b03a3a', moduleSpacing: 12 }),
    titleStyle: 'sidebar',
    profileStyle: 'left',
    pageStyle: 'single',
  },
]
