import type { ResumeTemplate } from '@/types/resume'
import { makeLayout, FONTS } from '../helper'
import './style.css'

/** 简约分类模板 */
export const minimalTemplates: ResumeTemplate[] = [
  {
    id: 'min-plain',
    name: '极简黑白',
    category: 'minimal',
    desc: '无装饰加粗标题，内容至上',
    className: 'tpl-min-plain',
    layout: makeLayout({}),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'min-compact',
    name: '紧凑排版',
    category: 'minimal',
    desc: '小字号窄间距，一页装下更多内容',
    className: 'tpl-min-compact',
    layout: makeLayout({
      fontSize: 12.5,
      lineHeight: 1.4,
      moduleSpacing: 7,
      itemSpacing: 4,
      pageMargin: 8,
    }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'min-banner',
    name: '浅色横带',
    category: 'minimal',
    desc: '浅灰蓝头部横带，视觉轻量',
    className: 'tpl-min-banner',
    layout: makeLayout({ themeColor: '#475569' }),
    titleStyle: 'plain',
    profileStyle: 'banner',
    pageStyle: 'single',
  },
  {
    id: 'min-table',
    name: '表格边框',
    category: 'minimal',
    desc: '表格式边框分区，模块信息一目了然',
    className: 'tpl-min-table',
    layout: makeLayout({ themeColor: '#2f3338', moduleSpacing: 12, itemSpacing: 8 }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'min-dot',
    name: '圆点极简',
    category: 'minimal',
    desc: '圆点引导标题，条目细分隔线，干净有节奏',
    className: 'tpl-min-dot',
    layout: makeLayout({ themeColor: '#374151', moduleSpacing: 16, itemSpacing: 8, pageMargin: 12, lineHeight: 1.6 }),
    titleStyle: 'plain',
    profileStyle: 'left',
    pageStyle: 'single',
  },
  {
    id: 'min-air',
    name: '留白呼吸',
    category: 'minimal',
    desc: '大间距大留白，阅读体验优先',
    className: 'tpl-min-air',
    layout: makeLayout({ themeColor: '#22262b', moduleSpacing: 18, itemSpacing: 10, pageMargin: 14, lineHeight: 1.7 }),
    titleStyle: 'plain',
    profileStyle: 'center',
    pageStyle: 'single',
  },
]
